# Contains the configuration for the whole server
# Dont set secrets, passwords, api_keys etc. in this file. Use '.env' file for that

maxProcess = 12 # Max number of cpu process to be used by go runtime 
gwDBRetention = 1
routerDBRetention = 0

[Gateway]
webPort = 8080
maxDBWriterProcess = 4
CustomVal = "GW"
maxBatchSize = 2
batchTimeoutInMS = 2
respMessage = "OK"


[JobsDB]
# Migration related parameters
jobDoneMigrateThres = 0.8
jobStatusMigrateThres = 5
maxDSSize = 100000
maxMigrateOnce = 10
mainCheckSleepDurationInS = 2

[Router]
jobQueryBatchSize = 10000
updateStatusBatchSize = 1
readSleepInMS = 10
noOfWorkers = 16
noOfJobsPerChannel = 1000
ser = 3
maxSleepInS = 3600
maxStatusUpdateWaitInS = 5
randomWorkerAssign = false
useTestSink = true
maxFailedCountForJob = 8

[Processor]
loopSleepInMS = 10
batchSize = 1000
sessionThresholdEvents = 20
sessionThresholdInS = 3
processSessions = false
maxChanSize = 2048
numTransformWorker = 8
maxRetry = 3
retrySleepInMS = 100

[SinkServer]
rate = 1000
burst = 10000


