version: '3.7'

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: loki
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: jobsdb
    ports:
      - "5432:5432"

  rudder:
    depends_on:
      - db
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JOBS_DB_PASSWORD=abc